# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BottleOrder(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BottleOrder()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBottleOrder(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BottleOrder
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BottleOrder
    def Sprite(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BottleOrder
    def Rootbeer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BottleOrder
    def Fanta(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def BottleOrderStart(builder):
    builder.StartObject(3)

def Start(builder):
    BottleOrderStart(builder)

def BottleOrderAddSprite(builder, sprite):
    builder.PrependUint32Slot(0, sprite, 0)

def AddSprite(builder, sprite):
    BottleOrderAddSprite(builder, sprite)

def BottleOrderAddRootbeer(builder, rootbeer):
    builder.PrependUint32Slot(1, rootbeer, 0)

def AddRootbeer(builder, rootbeer):
    BottleOrderAddRootbeer(builder, rootbeer)

def BottleOrderAddFanta(builder, fanta):
    builder.PrependUint32Slot(2, fanta, 0)

def AddFanta(builder, fanta):
    BottleOrderAddFanta(builder, fanta)

def BottleOrderEnd(builder):
    return builder.EndObject()

def End(builder):
    return BottleOrderEnd(builder)
