# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

class BreadType(object):
    WholeWheat = 0
    Pumpernickel = 1
    Rye = 2
    White = 3
    Sourdough = 4
