# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CanOrder(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CanOrder()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCanOrder(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CanOrder
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CanOrder
    def Coke(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CanOrder
    def Pepsi(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CanOrder
    def Coors(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def CanOrderStart(builder):
    builder.StartObject(3)

def Start(builder):
    CanOrderStart(builder)

def CanOrderAddCoke(builder, coke):
    builder.PrependUint32Slot(0, coke, 0)

def AddCoke(builder, coke):
    CanOrderAddCoke(builder, coke)

def CanOrderAddPepsi(builder, pepsi):
    builder.PrependUint32Slot(1, pepsi, 0)

def AddPepsi(builder, pepsi):
    CanOrderAddPepsi(builder, pepsi)

def CanOrderAddCoors(builder, coors):
    builder.PrependUint32Slot(2, coors, 0)

def AddCoors(builder, coors):
    CanOrderAddCoors(builder, coors)

def CanOrderEnd(builder):
    return builder.EndObject()

def End(builder):
    return CanOrderEnd(builder)
