# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Health(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Health()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHealth(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Health
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Health
    def SeqNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Health
    def Ts(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Health
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Health
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Health
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Health
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Health
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Health
    def Dispenser(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Health
    def Icemaker(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Health
    def Lightbulb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Health
    def FridgeTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Health
    def FreezerTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Health
    def SensorStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Health
    def Humidity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Health
    def DoorOpenings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HealthStart(builder):
    builder.StartObject(12)

def Start(builder):
    HealthStart(builder)

def HealthAddSeqNo(builder, seqNo):
    builder.PrependUint32Slot(0, seqNo, 0)

def AddSeqNo(builder, seqNo):
    HealthAddSeqNo(builder, seqNo)

def HealthAddTs(builder, ts):
    builder.PrependFloat64Slot(1, ts, 0.0)

def AddTs(builder, ts):
    HealthAddTs(builder, ts)

def HealthAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    HealthAddName(builder, name)

def HealthAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    HealthAddData(builder, data)

def HealthStartDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDataVector(builder, numElems: int) -> int:
    return HealthStartDataVector(builder, numElems)

def HealthAddDispenser(builder, dispenser):
    builder.PrependInt8Slot(4, dispenser, 0)

def AddDispenser(builder, dispenser):
    HealthAddDispenser(builder, dispenser)

def HealthAddIcemaker(builder, icemaker):
    builder.PrependInt32Slot(5, icemaker, 0)

def AddIcemaker(builder, icemaker):
    HealthAddIcemaker(builder, icemaker)

def HealthAddLightbulb(builder, lightbulb):
    builder.PrependInt8Slot(6, lightbulb, 0)

def AddLightbulb(builder, lightbulb):
    HealthAddLightbulb(builder, lightbulb)

def HealthAddFridgeTemp(builder, fridgeTemp):
    builder.PrependInt32Slot(7, fridgeTemp, 0)

def AddFridgeTemp(builder, fridgeTemp):
    HealthAddFridgeTemp(builder, fridgeTemp)

def HealthAddFreezerTemp(builder, freezerTemp):
    builder.PrependInt32Slot(8, freezerTemp, 0)

def AddFreezerTemp(builder, freezerTemp):
    HealthAddFreezerTemp(builder, freezerTemp)

def HealthAddSensorStatus(builder, sensorStatus):
    builder.PrependInt8Slot(9, sensorStatus, 0)

def AddSensorStatus(builder, sensorStatus):
    HealthAddSensorStatus(builder, sensorStatus)

def HealthAddHumidity(builder, humidity):
    builder.PrependFloat64Slot(10, humidity, 0.0)

def AddHumidity(builder, humidity):
    HealthAddHumidity(builder, humidity)

def HealthAddDoorOpenings(builder, doorOpenings):
    builder.PrependUint32Slot(11, doorOpenings, 0)

def AddDoorOpenings(builder, doorOpenings):
    HealthAddDoorOpenings(builder, doorOpenings)

def HealthEnd(builder):
    return builder.EndObject()

def End(builder):
    return HealthEnd(builder)
