# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

class MeatType(object):
    GroundBeef = 0
    Chicken = 1
    Turkey = 2
    Ham = 3
    Pork = 4
    Steak = 5
