# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

class MilkType(object):
    OnePercent = 0
    TwoPercent = 1
    FatFree = 2
    Whole = 3
    Almond = 4
    Cashew = 5
    Oat = 6
